config/routes.rb
Rails.application.routes.draw do
  
  resources :updates

  resources :specialcontests

  resources :sponsorships

  resources :problems

  root :to => "contests#index"
  resources :entries
  resources :entries do
    member do
      post 'upvote'
      post 'overide'
      post 'testupvote'
    end
  end
  
  resources :results 
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
  get "/pages/:page" => "pages#show"
  get "/myentries" => "entries#mycontest"
  get "/admin" => "users#admin"
  get "/contestlist" => "contests#contestlist"
  get "/entrylist" => "entries#entrylist"
  get "/conentries" => "entries#conentries"
  get "/userlist" => "users#userlist"
  get "/users/edit/:id" => "users#edit"
  get "/winners" => "results#winners"
  get "makeadmin" => "users#makeadmin"
  get "makeparticipant" => "users#makeparticipant"
  resources :contests do
    resources :entries
  end

  match '*path' => 'errors#error_404', via: :all

  

end

app/models/entry.rb
class Entry < ActiveRecord::Base
  belongs_to :contest
  has_many :votes, dependent: :destroy
  belongs_to :user
  has_many :upvoted_users, through: :votes, source: :user

  validates :caption,:mobile,:email, :presence => true
  validates :mobile, :numericality =>  {:only_integer=>true, :message => ' is invalid.'}
  validates :mobile, length:{ minimum: 10 }

  scope :recent, -> {order("entries.created_at DESC")}
  scope :by_status, -> status { where(status: status) }

  	has_attached_file :image, styles: { medium: "300x300", thumb: "100x100" }
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  	validates_attachment_file_name :image, matches: [/png\Z/, /jpe?g\Z/, /JPE?G\Z/]
  	validates :image, :presence => true
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: :show
  layout "entry", only: [:show]
  # GET /entries
  # GET /entries.json
  def index
    @entry = Entry.all
    @entries = Entry.paginate(:page=>params[:page],:per_page=>10).recent
    #@entries = Entry.all
  end

  def conentries
    if params[:search]
        @contests = Contest.search(params[:search]).order("created_at DESC")
        if @contests == ""
          flash[:notice] = "Contests not found, please check id"
        end
    end
    #@entries = Entry.where('contest_id = ?',params[:search]).limit(20)
    @conentries = Entry.where('contest_id = ?', params[:search]).paginate(:page=>params[:page],:per_page=>10).recent
  end

  def entrylist
    if current_user && current_user.admin?
      @entries = Entry.paginate(:page=>params[:page],:per_page=>10).recent
    else
      flash[:notice] = "No such page exists"
      redirect_to root_path
    end
  end

  def mycontest
    @user = User.find(current_user.id)
    @userentries = Entry.where(user_id: @user)
    if @userentries.blank?
      render "entries/nocontests"
    end
  end
  # GET /entries/1
  # GET /entries/1.json
  def show
    @relentry = Entry.by_status('Approved').where(contest_id: @entry.contest_id)
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
    if current_user && current_user.admin?
    else
      flash[:notice] = "No such page exists"
      redirect_to root_path
    end
  end

  # POST /entries
  # POST /entries.json
  def create
    @contest = Contest.find(params[:contest_id])
    params[:entry][:status]="Submitted"
    params[:entry][:user_id]=current_user.id
    @entry = @contest.entries.create(entry_params)
    if @entry.save
      redirect_to entry_path(@entry)
      flash[:success] = "Entry submitted successfully"
      require 'msg91ruby'
      api = Msg91ruby::API.new("155559AcDj9QWtpxN5939806a","KRAZYK")
      api.send(params[:entry][:mobile], "Thank you, #{current_user.name}, for participating in our contest. Here is your link \"http://www.krazykontest.com#{entry_path(@entry)}\". Start collecting votes to win prizes. Follow us fb.com/krazykontests", 4)
    else
      flash[:error] = "All fields are mandatory"
      redirect_to :back
    end
  end

  #voting 
  def upvote
    @entry = Entry.find(params[:id])
    @success=@entry.votes.create(user_id: current_user.id)
    if @success.save
      flash[:notice] =  "Thank you for upvoting!"
      redirect_to :back
    else 
      flash[:notice] =  "You have already upvoted this!"
      redirect_to :back
    end
    #@entry.votes.create
    #redirect_to(entries_path)
    #redirect_to :back
  end

  # PATCH/PUT /entries/1
  # PATCH/PUT /entries/1.json
  def update    
    respond_to do |format|
      if params[:entry][:status] == 'Rejected'
        if @entry.update(entry_params)
          require 'msg91ruby'
          api = Msg91ruby::API.new("155559AcDj9QWtpxN5939806a","KRAZYK")
          api.send(@entry.mobile, "Dear participant, We are sorry to inform you that your entry is invalid. Read our description and steps properly and do participate again. Regards Krazykontest", 4)
          format.html { redirect_to "/entries", notice: 'Entry was successfully updated - Reject SMS.' }
          format.json { render :show, status: :ok, location: @entry }
        end
          format.html { redirect_to "/entries", notice: 'Entry was successfully updated.' }
          format.json { render :show, status: :ok, location: @entry }
      else
        params[:entry][:rejected_reason] = ""
        if @entry.update(entry_params)
          format.html { redirect_to "/entries", notice: 'Entry was successfully updated - No SMS.' }
          format.json { render :show, status: :ok, location: @entry }
        else
          format.html { render :edit }
          format.json { render json: @entry.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  def overide
    @user=User.find(current_user.id)
    @entry=Entry.find(params[:id])
    params[:entry][:entryvotes] = params[:entryvotes]
    respond_to do |format|
      if @entry.update_attributes(:entryvotes)
        flash[:notice] =  "Vote counts updated successfully."
        redirect_to "/results"
        #format.html { redirect_to "/results", notice: 'Vote counts updated successfully.' }
        #format.json { render :show, status: :ok, location: @entry }
      else
        flash[:notice] =  "Not Editable"
        #format.html { render :edit }
        #format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to entries_url, notice: 'Entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entry_params
      params.require(:entry).permit(:contest_id, :uploaded_image,:image, :uploaded_video, :caption, :mobile, :email, :shares, :status, :rejected_reason,:user_id,:entryvotes)
    end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_entries.html.erb
<div class="field">
  <%= f.label :uploaded_image %><br>
  <%= f.text_field :uploaded_image %>
</div>
<div class="field">
  <%= f.label :uploaded_video %><br>
  <%= f.text_field :uploaded_video %>
</div>
<div class="field">
  <%= f.label :caption %><br>
  <%= f.text_field :caption %>
</div>
<div class="field">
  <%= f.label :mobile %><br>
  <%= f.text_field :mobile %>
</div>
<div class="field">
  <%= f.label :email %><br>
  <%= f.text_field :email %>
</div>
<div class="actions">
  <%= f.submit %>
</div>

app/views/entries/_form.html.erb
<%= form_for(@entry, html: {class: "custom-form"}) do |f| %>
  <% if @entry.errors.any? %>
    <div class="col s12 m12 l12">
      <div id="error_explanation">
        <h2><%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

        <ul>
        <% @entry.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>
<div class="form-horizontal">
  <div class="form-group">
    <%= f.label :contest_id,:class=>"control-label col m3 l3" %>
    <%= f.text_field :contest_id,:class=>"form-control col m6 l6",:disabled=>"true" %>
    <span class="col m3 l3">&nbsp;</span>
  </div>
  <div class="form-group">
    <%= f.label :image,:class=>"control-label col m3 l3" %>
    <%= f.file_field :image,:class=>"col m3 l3" %>
    <span class="col m3 l3">
      <% if @entry.image? %>
      <%= image_tag @entry.image.url(:thumb) %>
    <% end %>
    </span>
    <span class="col m3 l3">&nbsp;</span>
  </div>
  <div class="form-group">
    <%#= f.label :uploaded_video,:class=>"control-label col m3 l3" %>
    <%#= f.file_field :uploaded_video,:class=>"col m6 l6" %>
    <span class="col m3 l3">&nbsp;</span>
  </div>
  <div class="form-group">
    <%= f.label :caption,:class=>"control-label col m3 l3" %>
    <%= f.text_field :caption,:class=>"form-control col m6 l6" %>
    <span class="col m3 l3">&nbsp;</span>
  </div>
  <div class="form-group">
    <%= f.label :mobile,:class=>"control-label col m3 l3" %>
    <%= f.text_field :mobile,:class=>"form-control col m6 l6" %>
    <span class="col m3 l3">&nbsp;</span>
  </div>
  <div class="form-group">
    <%= f.label :email,:class=>"control-label col m3 l3" %>
    <%= f.text_field :email,:class=>"form-control col m6 l6" %>
    <span class="col m3 l3">&nbsp;</span>
  </div>
  <div class="form-group">
    <%= f.label :entryvotes,:class=>"control-label col m3 l3" %>
    <%= f.text_field :entryvotes,:class=>"form-control col m6 l6" %>
    <span class="col m3 l3">&nbsp;</span>
  </div>
  <div class="form-group">
    <%= f.label :shares,:class=>"control-label col m3 l3" %>
    <%= f.text_field :shares,:class=>"form-control col m6 l6" %>
    <span class="col m3 l3">&nbsp;</span>
  </div>
  <div class="form-group">
    <%= f.label :status,:class=>"control-label col m3 l3" %>
    <div class="col m6 l6">
      <%= f.select :status,['Pending Approval','Approved','Rejected'],:class=>"form-control" %>
    </div>
    <span class="col m3 l3">&nbsp;</span>
  </div>
  <div class="form-group">
    <%= f.label :rejected_reason,:class=>"control-label col m3 l3" %>
    <%= f.text_field :rejected_reason,:class=>"form-control col m6 l6" %>
    <span class="col m3 l3">&nbsp;</span>
  </div>
  <div class="actions center">
    <%= f.submit "Add Entries",:class=>"btn waves-effect waves-light" %>
  </div>
  <div class="right">
    <%#= link_to 'Show', @entry %> |
    <%= link_to 'Back', url_for(:back)%><%#entries_path %>
  </div>
</div>
<% end %>

app/views/entries/conentries.html.erb
<div class="col s12 m12 l12 center">
  <div class="col hide-on-small-and-down m1 l1 center">&nbsp;</div>
    <div class="col s12 m10 l10">
    <% if notice %>
      <p id="notice"><%= notice %></p>
    <% end %>
    </div>
  <div class="col hide-on-small-and-down m1 l1 center">&nbsp;</div>
</div>
<div class="col hide-on-small-and-below m1 l1">&nbsp;</div>
<div class="col s12 m10 l10 condesc" style="font-size:14px;">
  <div class="center">
    <h5>Find By Contest Id</h5>
    <hr>
    <div class="col s3 m3 l3">&nbsp;</div>
    <div class="col s6 m6 l6">
      <%= form_tag(conentries_path, :method => "get", id: "search-form") do %>
        <div class="col s6 m6 l6">
          <%= text_field_tag :search, params[:search], placeholder: "Enter Contest ID" %>
        </div>
        <div class="col s6 m6 l6 left-align">
          <%= submit_tag "Search", :class=>"btn" %>
        </div>
      <% end %>
    </div>
    <div class="col s3 m3 l3">&nbsp;</div>
  </div>
  <div class="col s12 m12 l12 center" style="margin-top:5%;">
    <% if @contests.present? %>
      <%#= render "results/winnerlist" %>
  <div class="condesc">
  <table class="table-responsive bordered highlight">
    <thead>
      <tr>
        <th>Contest Id</th>
        <th width="15%">Image/Video</th>
        <th>Participant Info</th>
        <th>Votes</th>
        <th>Status</th>
        <th>Rejected reason</th>
        <th>Action</th>
      </tr>
    </thead>

    <tbody class="krtext">
      <% @conentries.each do |entry| %>
        <tr>
          <td>
            <%#= entry.contest.title %>
            <%= image_tag(entry.contest.image.url(:thumb),:class=>'responsive-img') %>
          </td>
          <td>
            <%if entry.image %>
              <%= image_tag(entry.image.url(:thumb), :class=>"relatedimg responsive-image") %>
            <%else%>
              <p>No Image</p>
            <%end%>
            <%#if entry.uploaded_video %>
              <%#= image_tag(entry.uploaded_video, :class=>"relatedimg responsive-image") %>
            <%#else%>
              <!--p>No Image</p-->
            <%#end%>
            <div class="conimage">
              <p><%= entry.caption %></p>
            </div>
          </td>        
          <td>
            <%= entry.mobile %><br>
            <%= entry.email %>
          </td>
          <td>
            <% if entry.entryvotes == "" || entry.entryvotes.blank? %>
              <%if entry.votes %>
                <%= entry.votes.count %>
              <%else%>
                <p>No Votes yet</p>
              <%end%>
            <%else%>
              <%= entry.entryvotes.to_i + entry.votes.count %>
            <% end -%>
            <%#if entry.shares %>
              <%#= entry.shares.to_s %>
            <%#else%>
              <!--p>No Shares yet</p-->
            <%#end%>
          </td>
          <td><%= entry.status %></td>
          <td>
            <% if entry.rejected_reason!="Select Reason" %>
              <%= entry.rejected_reason %>
            <%end%>
          </td>
          <td>
            <%= link_to 'Show', entry %><br>
            <% if current_user.admin? %>
            <%= link_to 'Edit', edit_entry_path(entry) %><br>
            <%#= link_to 'Select As Winner', "/" %>
            <%= link_to 'Destroy', entry, method: :delete, data: { confirm: 'Are you sure?' } %><br>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
  <%#= link_to 'Add Entry', new_entry_path,:class=>"center btn waves-effect waves-light"  %>
</div>
    <% else %>
      <p class="center red-text">
        Please enter valid contest id to find top entries.<%#= params[:search] %>.
      </p>
    <% end %>
  </div>
</div>
<div class="col s12 m10 l10 pagination" style="text-align:right">
   <%= will_paginate @conentries, renderer: BootstrapPagination::Rails %>
</div>
<div class="col hide-on-small-and-below m1 l1">&nbsp;</div>

app/views/entries/entrylist.html.erb
<div class="col s12 m12 l12">
  <div class="col hide-on-small-and-down m1 l1 center">&nbsp;</div>
    <div class="col s12 m10 l10">
    <% if notice %>
      <p id="notice"><%= notice %></p>
    <% end %>
    </div>
  <div class="col hide-on-small-and-down m1 l1 center">&nbsp;</div>
</div>
<div class="col hide-on-small-and-below m1 l1">&nbsp;</div>
<div class="col s12 m10 l10">
  <div class="center">
    <h5>Entries</h5><%= link_to "Admin Panel","/admin" %>
  </div>
  <div class="condesc">
  <table class="table-responsive bordered highlight">
    <thead>
      <tr>
        <th width="15%">Contest</th>
        <th width="15%">Image</th>
        <th>Participant Info</th>
        <th>Votes</th>
        <th>Status</th>
        <th>Rejected reason</th>
        <th>Action</th>
      </tr>
    </thead>

    <tbody class="krtext">
      <% @entries.each do |entry| %>
        <tr>
          <td>
            <%#= entry.contest.title %>
            <%= link_to(image_tag(entry.contest.image,:class=>'relatedimg responsive-img'),"/contests/#{entry.contest.id}") %>
          </td>
          <td>
            <%if entry.image %>
              <%= image_tag(entry.image, :class=>"relatedimg responsive-image") %>
            <%else%>
              <p>No Image</p>
            <%end%>
            <%#if entry.uploaded_video %>
              <%#= image_tag(entry.uploaded_video, :class=>"relatedimg responsive-image") %>
            <%#else%>
              <!--p>No Image</p-->
            <%#end%>
            <div class="conimage">
              <p><%= entry.caption %></p>
            </div>
          </td>        
          <td>
            <%= entry.mobile %><br>
            <%= entry.email %>
          </td>
          <td>
            Actual Votes : <span style="color:green;"><%= entry.votes.count %></span><br>
            Overridden To: <span style="color:green;"><%= entry.entryvotes %></span><br>
            Total Votes  : <span style="color:green;"><b><%= entry.entryvotes.to_i + entry.votes.count %></b></span>

            <%#if entry.entryvotes %>
              <%#= entry.entryvotes %>
            <%#else%>
              <%#if entry.votes %>
                <%#= entry.votes.count %>
              <%#else%>
                <!--p>No Votes yet</p-->
              <%#end%>
            <%#end%>
            <%#if entry.shares %>
              <%#= entry.shares.to_s %>
            <%#else%>
              <!--p>No Shares yet</p-->
            <%#end%>
          </td>
          <td><%= entry.status %></td>
          <td>
            <% if entry.status == 'Rejected'%>
              <%= entry.rejected_reason %>
            <%end%>
          </td>
          <td>
            <%= link_to 'Show', entry %><br>
            <%= link_to 'Overide Votes', edit_entry_path(entry) %><br>
            <%#= link_to 'Select As Winner', "/" %>
            <%#= link_to 'Destroy', entry, method: :delete, data: { confirm: 'Are you sure?' } %><br>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
  <%#= link_to 'Add Entry', new_entry_path,:class=>"center btn waves-effect waves-light"  %>
</div>
</div>
<div class="col s12 m10 l10 pagination" style="text-align:right">
   <%= will_paginate @entry, renderer: BootstrapPagination::Rails %>
</div>
<div class="col hide-on-small-and-below m1 l1">&nbsp;</div>

app/views/entries/index.html.erb
<div class="col s12 m12 l12">
  <p id="notice"><%= notice %></p>
</div>
<div class="col hide-on-small-and-below m1 l1">&nbsp;</div>
<div class="col s12 m10 l10">
  <div class="center">
    <h5>Entries</h5><% if current_user.admin? %><%= link_to "Admin Panel","/admin" %><%end%>
  </div>
  <div class="condesc">
  <table class="table-responsive bordered highlight">
    <thead>
      <tr>
        <th>Contest Id</th>
        <th width="15%">Image/Video</th>
        <th>Participant Info</th>
        <th>Votes</th>
        <th>Status</th>
        <th>Rejected reason</th>
        <th>Action</th>
      </tr>
    </thead>

    <tbody class="krtext">
      <% @entries.each do |entry| %>
        <tr>
          <td>
            <%#= entry.contest.title %>
            <%= image_tag(entry.contest.image,:class=>'responsive-img') %>
          </td>
          <td>
            <%if entry.image %>
              <%= image_tag(entry.image, :class=>"relatedimg responsive-image") %>
            <%else%>
              <p>No Image</p>
            <%end%>
            <%#if entry.uploaded_video %>
              <%#= image_tag(entry.uploaded_video, :class=>"relatedimg responsive-image") %>
            <%#else%>
              <!--p>No Image</p-->
            <%#end%>
            <div class="conimage">
              <p><%= entry.caption %></p>
            </div>
          </td>        
          <td>
            <%= entry.mobile %><br>
            <%= entry.email %>
          </td>
          <td>
            <%if entry.votes %>
              <%= entry.votes.count %>
            <%else%>
              <p>No Votes yet</p>
            <%end%>
            <%#if entry.shares %>
              <%#= entry.shares.to_s %>
            <%#else%>
              <!--p>No Shares yet</p-->
            <%#end%>
          </td>
          <td><%= entry.status %></td>
          <td>
            <% if entry.rejected_reason!="Select Reason" %>
              <%= entry.rejected_reason %>
            <%end%>
          </td>
          <td>
            <%= link_to 'Show', entry %><br>
            <% if current_user.admin? %>
            <%= link_to 'Edit', edit_entry_path(entry) %><br>
            <%#= link_to 'Select As Winner', "/" %>
            <%= link_to 'Destroy', entry, method: :delete, data: { confirm: 'Are you sure?' } %><br>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
  <%#= link_to 'Add Entry', new_entry_path,:class=>"center btn waves-effect waves-light"  %>
</div>
</div>
<div class="col s12 m10 l10 pagination" style="text-align:right">
   <%= will_paginate @entries, renderer: BootstrapPagination::Rails %>
</div>
<div class="col hide-on-small-and-below m1 l1">&nbsp;</div>

app/views/entries/new.html.erb
<div class="col hide-on-small-and-below m2 l2">&nbsp;</div>
<div class="col s12 m8 l8">
	<div class="center">
		<h4>New Entry</h4>
	</div>
	<div>
		<%= render 'form' %>
	</div>
	<div>
		<%= link_to 'Back', entries_path %>
	</div>
</div>
<div class="col hide-on-small-and-below m2 l2">&nbsp;</div>

app/views/entries/nocontests.html.erb
<div class="col s12 m12 l12">
  <p id="notice"><%= notice %></p>
</div>
<div class="col hide-on-small-and-below m1 l1">&nbsp;</div>
<div class="col s12 m10 l10">
  <div class="center">
    <%= image_tag(@user.image,:class=>"responsive-img profile-pic") %>
  </div>
  <div class="center">
    <h5>My Entries</h5>
  </div>
  <div class="blankdata">
    <p class="nocontest center">You haven't participated in any contest. <%= link_to "Click here","/" %> for ongoing contest lists</p>
  </div>
</div>
<div class="col hide-on-small-and-below m1 l1">&nbsp;</div>

app/views/entries/show.html.erb
<% title @entry.caption %>
<% meta_description @entry.caption.truncate(150, separator: ' ') %>
<% content_for :head do %>
   <meta name='url' content='http://www.krazykontest.com/entries/<%= @entry.id %>' />
   <meta property="fb:app_id" content="679404752227654" />
    <meta name="google-site-verification" content="E7-XuYKm1EfX_zWIR1Bs-m0xCGHsqi9cMQhcuhrcILA" />
    <meta property="og:title" content="<%= @entry.caption %>" />
    <meta property="og:url" content="http://www.krazykontest.com/entries/<%= @entry.id%>" />
    <meta property="og:description" content="<%= @entry.caption %>" />
    <meta property="og:image" content='<%= @entry.image %>' />
<%end%>
<div id="fb-root"></div>
<script>
  (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.8&appId=679404752227654";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));
</script>
<script type="text/javascript">
  $("#vote").click(function(){
        $("#vote").hide();
        $("#voted").show();
      }); 
</script>
<div class="col s12 m12 l12 center">
  <% if notice %>
    <p id="notice"><%= notice %></p>
  <% end %>
  <!--p id="success"><%#= success %></p-->
</div>
<div class="col hide-on-small-and-below m2 l2">&nbsp;</div>
<div class="col s12 m8 l8" style="">  
  <div class="col s12 m12 l12">
    <div class="center">
      <%= image_tag(@entry.image,:class=>'responsive-img center',:"max-width"=>'100%') %>
    </div>
    <div class="col s12 m9 l9" style="margin-top:2%">
      Caption : <b><%= @entry.caption %></b>
    </div>
    <div class="col s12 m3 l3" style="margin-top:2%;text-align:right">
      <%if @entry.entryvotes %>
        <%= pluralize(@entry.entryvotes.to_i + @entry.votes.count,"vote") %>
      <%else%>
        <%= pluralize(@entry.votes.count, "vote") %> |  
      <%end%>      
      <% if @entry.contest.status == "Active" || @entry.contest.status == "active" %>
        <% if !user_signed_in? %>
          <%= link_to "Login to Vote", user_facebook_omniauth_authorize_path,:class=>"logbutton" %> 
        <%else%>
          <%= link_to(image_tag("icons/Vote.png",:class=>"responsive-img",:width=>'25%'),upvote_entry_path(@entry),method: :post,:id=>"vote") %>
        <%end%>
      <%else%>
        <span style="color:red;">Contest Closed</span>
      <%end%>
    </div>
    <div class="col s12 m7 l7" style="margin-top:10px;">
      Participant Name : <b><%= @entry.user.name %></b>
    </div>
    <div class="col s12 m5 l5" style="text-align:right;margin-top:10px;">
      <div class="fb-share-button" data-layout="button_count" data-size="small" data-mobile-iframe="false">
        <a class="fb-xfbml-parse-ignore" target="_blank" ></a>
      </div> &nbsp;
      <a class="twitter-share-button" href="https://twitter.com/intent/tweet?text=Check my entry http://www.krazykontest.com/entries/<%= @entry.id %> &hashtags=krazykontest" data-size="large"><i class="fa fa-twitter"></i>Tweet</a> &nbsp;
      <a class="watsapp-share-button hide-on-large-only" href="whatsapp://send?text=Hey! check my entry and please upvote, http://www.krazykontest.com/entries/<%=@entry.id%>" data-action="share/whatsapp/share"> Whatsapp</a>
      
    </div>
  </div>
  <div class="col s12 m12 l12 center" style="margin-top:2%">
    <h5><span class='heading'>Related Entries</span></h5>
  </div>
  <div class="col s12 m12 l12" style="margin-top:2%">
    <% @relentry.each do |relentry| %>
    <% if relentry.id != @entry.id %>
      <div class="col s6 m3 l3">
        <div class="card">
          <div class="card-image">
            <%= link_to(image_tag(relentry.image, :class=>'responsive-img',:style=>"padding:2px"),"/entries/#{relentry.id}") %>
          </div>
          <div class="center">
            <p><%= relentry.caption %></p>
          </div>
        </div> 
      </div>
    <% end %>
    <%end%>
  </div>
</div>
<div class="col hide-on-small-and-below m2 l2">&nbsp;</div>