config/routes.rb
Rails.application.routes.draw do
  
  resources :updates

  resources :specialcontests

  resources :sponsorships

  resources :problems

  root :to => "contests#index"
  resources :entries
  resources :entries do
    member do
      post 'upvote'
      post 'overide'
      post 'testupvote'
    end
  end
  
  resources :results 
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
  get "/pages/:page" => "pages#show"
  get "/myentries" => "entries#mycontest"
  get "/admin" => "users#admin"
  get "/contestlist" => "contests#contestlist"
  get "/entrylist" => "entries#entrylist"
  get "/conentries" => "entries#conentries"
  get "/userlist" => "users#userlist"
  get "/users/edit/:id" => "users#edit"
  get "/winners" => "results#winners"
  get "makeadmin" => "users#makeadmin"
  get "makeparticipant" => "users#makeparticipant"
  resources :contests do
    resources :entries
  end

  match '*path' => 'errors#error_404', via: :all

  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :contests
  has_many :votes, dependent: :destroy
  has_many :upvoted_entries, through: :votes, source: :entries

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, :omniauth_providers => [:facebook]
  
  scope :recent, -> {order("users.created_at DESC")}
  #scope :result, -> {order("users.created_at DESC")}

  def self.from_omniauth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        if(auth.info.email)
          user.email = auth.info.email  
        else
          user.email="#{auth.uid}@krazykontest.com"
        end        
        user.name = auth.info.name
        user.password = Devise.friendly_token[0,20]
        if (auth.info.image)
          user.image = auth.info.image
        else
          user.image = "/missing.png"
        end
      end
  end

  def admin?
    self.role == 'admin' || self.role=='Admin'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :authenticate_user!, only: [:index]
	before_filter do
		redirect_to "/" unless current_user && current_user.admin?
	end

	def index
		render template: "user/admin"
	end

	def userlist
	  @users = User.paginate(:page=>params[:page],:per_page=>10).recent
	end

	def edit
	end

	def update
    respond_to do |format|
      if @user.update(params[:role])
        format.html { redirect_to @user, notice: 'User updated successfully.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  	end

  	#make admin user
  	def makeadmin
  		@user=User.find(params[:id])
  		if @user.role != 'admin'
  			@user.update_attributes(:role => 'admin')
  			flash[:notice] = "#{@user.name} is marked as Admin now"  			
  		end
  		if @user.role == "admin" || @user.role == "Admin"
  			flash[:notice] = "#{@user.name} is already Admin"
  		else
  			flash[:notice] = "Something went wrong"
  		end
      redirect_to "/userlist"
  	end

  	#make normal user
  	def makeparticipant
  		@user=User.find(params[:id])
  		if @user.role != 'participant'
  			@user.update_attributes(:role => 'participant')
  			flash[:notice] = "#{@user.name} is marked as Normal user now"
  		end
  		if @user.role == "participant" || @user.role == "participant"
  			flash[:notice] = "Role of #{@user.name} is already Participant"
  		else
  			flash[:notice] = "Something went wrong"
  		end
      redirect_to "/userlist"
  	end
end

app/views/users/admin.html.erb
<div class="col s12 m12 l12 center">
  <div class="col hide-on-small-and-down m1 l1 center">&nbsp;</div>
    <div class="col s12 m10 l10">
    <% if notice %>
      <p id="notice"><%= notice %></p>
    <% end %>
    </div>
    <div class="col hide-on-small-and-down m1 l1 center">&nbsp;</div>
</div>
<div class="col hide-on-small-and-below m2 l2">&nbsp;</div>
<div class="center col s12 m8 l8 condesc">
	<div style="margin-bottom:2%;">
		<h5>Admin Panel</h5>
	</div>
	<table class="responsive-table">
		<tr>
			<td class="center">
				<%= link_to "Add Contest", new_contest_path, :class=>"btn btn-small waves"%>
			</td>
			<td class="center">
				<%= link_to "Contest List", "/contestlist", :class=>"btn btn-small waves"%>
			</td>
			<td class="center">
				<%= link_to "User List", "/userlist", :class=>"btn btn-small waves"%>
			</td>
			<td class="center">
				<%= link_to "Entry List", "/entrylist", :class=>"btn btn-small waves"%>
			</td>
		</tr>
		<tr>
			<td class="center">
				<%= link_to "Overide Votes", results_path, :class=>"btn btn-small waves"%>
			</td>
			<td class="center">
				<%= link_to "Contacts", problems_path, :class=>"btn btn-small waves"%>
			</td>
			<td class="center">
				<%= link_to "ConEntries", conentries_path, :class=>"btn btn-small waves"%>
			</td>			
			<td class="center">
				<%= link_to "Sponsorships", sponsorships_path, :class=>"btn btn-small waves"%>
			</td>
		</tr>
	</table>	
</div>
<div class="col hide-on-small-and-below m2 l2">&nbsp;</div>

app/views/users/edit.html.erb
<%= form_for(@user, html: {class: "custom-form"}) do |f| %>
  <% if @user.errors.any? %>
    <div class="col s12 m12 l12">
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>
<div class="form-horizontal">
  <div class="form-group">
    <%= f.label :role,:class=>"control-label col m3 l3" %>
    <div class="col m6 l6">
      <%= f.select :role,['Select Role','Participant','Admin'],:class=>"form-control" %>
    </div>
    <span class="col m3 l3">&nbsp;</span>
  </div>
  <div class="actions center">
    <%= f.submit "Update user",:class=>"btn waves-effect waves-light" %>
  </div>
  <div class="right">
    <%#= link_to 'Show', @user %>
    <%= link_to 'Back', url_for(:back)%><%#entries_path %>
  </div>
</div>
<% end %>

app/views/users/notadmin.html.erb
<div class="col s12 m12 l12 center">
  <p id="notice"><%= notice %></p>
</div>
<div class="col hide-on-small-and-below m2 l2">&nbsp;</div>
<div class="col s12 m8 l8 blankdata">
	<p class="nocontest center">You are not admin.</p>
</div>
<div class="col hide-on-small-and-below m2 l2">&nbsp;</div>

app/views/users/show.html.erb
<div class="col s12 m12 l12 center">
  <p id="notice"><%= notice %></p>
</div>
<div class="col hide-on-small-and-below m2 l2">&nbsp;</div>
<div class="col s12 m8 l8">
	<%= link_to "Add Contest", new_contest_path, :class=>"btn btn-small waves"%>
</div>
<div class="col hide-on-small-and-below m2 l2">&nbsp;</div>

app/views/users/userlist.html.erb
<div class="col s12 m12 l12 center">
  <p id="notice"><%= notice %></p>
</div>
<div class="col hide-on-small-and-below m1 l1">&nbsp;</div>
<div class="col s12 m10 l10 condesc" style="font-size:14px;">
	<div class="center">
		<h5>List of Users</h5><%= link_to "Admin Panel","/admin" %>
	</div>
	<table class="table-bordered">
	<tr>
		<th width="8%">Id</th>
		<th width="20%">UID</th>
		<th width="17%">Name/Pic</th>
		<th width="12%">Role</th>		
		<th width="8%">Provider</th>
		<th width="20%">SignIn Details</th>
		<th width="15%">Actions</th>
	</tr>
	<% @users.each do |user| %>
	<tr>
		<td><%= user.id %></td>
		<td><%= user.uid %></td>
		<td><%= image_tag(user.image, :width=>"50px;")%><br><%= user.name %></td>
		<td><%= user.role %></td>
		<td><%= user.provider %></td>
		<td>
			<span style="color:grey">Last Sign in</span> : <%= user.last_sign_in_at.to_date %><br>
			<span style="color:grey">Last Sign Ip</span> : <%= user.last_sign_in_ip %><br>
			<span style="color:grey">Signed Up At</span> : <%= user.created_at.to_date %><br>
			<span style="color:grey">Sign Count</span> : <%= user.sign_in_count %>
		</td>
		<td>
			<%= link_to 'Make Admin', :controller=> "users", :action=>"makeadmin", :id => user.id %><br>
        	<%= link_to 'Make Normal', :controller=> "users", :action=>"makeparticipant", :id => user.id %>
        	<%#= link_to 'Show', contest %>
        	<%#= link_to 'Edit', "#" %><%#/users/edit/#{user.id}" %>
        	<%#= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %>
		</td>
	</tr>
	<% end %>
	</table>
</div>
<div class="col s12 m10 l10 pagination" style="text-align:right">
   <%= will_paginate @user, renderer: BootstrapPagination::Rails %>
</div>
<div class="col hide-on-small-and-below m1 l1">&nbsp;</div>