config/routes.rb
Rails.application.routes.draw do
  
  resources :updates

  resources :specialcontests

  resources :sponsorships

  resources :problems

  root :to => "contests#index"
  resources :entries
  resources :entries do
    member do
      post 'upvote'
      post 'overide'
      post 'testupvote'
    end
  end
  
  resources :results 
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
  get "/pages/:page" => "pages#show"
  get "/myentries" => "entries#mycontest"
  get "/admin" => "users#admin"
  get "/contestlist" => "contests#contestlist"
  get "/entrylist" => "entries#entrylist"
  get "/conentries" => "entries#conentries"
  get "/userlist" => "users#userlist"
  get "/users/edit/:id" => "users#edit"
  get "/winners" => "results#winners"
  get "makeadmin" => "users#makeadmin"
  get "makeparticipant" => "users#makeparticipant"
  resources :contests do
    resources :entries
  end

  match '*path' => 'errors#error_404', via: :all

  

end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
	before_action :authenticate_user!
	helper_method :sort_column, :sort_direction

	def index
		@votes = Vote.group("entry_id")
		@entry=Entry.paginate(:page=>params[:page],:per_page=>10).recent
	end

	def winners
		#@contests = Contest.all
		if params[:search]
		    @contests = Contest.search(params[:search]).order("created_at DESC")
		    if @contests == ""
		    	flash[:notice] = "Contests not found, please check id"
		    else
		    	@entries = Entry.find_by_sql("SELECT e.*, if(e.entryvotes is NULL, count(v.id), e.entryvotes + count(v.id)) as vote_count from entries e inner join votes v on e.id = v.entry_id where e.contest_id=#{params[:search]} and e.status = 'Approved' group by e.id order by vote_count DESC limit 20")
		    	if !@entries
					flash[:notice] = "No Entries found"
				end
			end
		end
		#@entries = Entry.where('contest_id = ?',params[:search]).limit(20)
		
		#@entries = Entry.find_by_sql("SELECT e.*, if(e.entryvotes is NULL, count(v.id), e.entryvotes) as vote_count from entries e inner join votes v on e.id = v.entry_id where e.contest_id=#{params[:search]} order by vote_count DESC").limit(20)
		
		#@entries.sort { |e1,e2| e1.votes.length <=> e2.votes.length }
		
	end
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/results/_winnerlist.html.erb
<% @contests.each do |contest| %>
<p>
	<b>Top entries</b>(max 20)<b> for <%= contest.title.camelize %> (Contest-Id: <%= link_to(contest.id,contest_path(contest.id)) %>) are:</b>
</p>
	<table class="table-responsive table-bordered sortable	" style="padding:5px;">
		<tr>
			<th width="13%">Winner Places</th>
			<th width="31%">Entry</th>
			<th width="31%">Participant Email</th>
			<th width="25%">Total Votes</th>
		</tr>		
		<% @entries.each_with_index do |entry, i| %>
		<tr>
			<td class="center">
				<%= (i+1) %>
			</td>
			<td>
				<%= link_to(image_tag(entry.image.url(:thumb)),entry_path(entry.id)) %>
				<%#= image_tag(entry.image, :class=> :medium) %>
			</td>
			<td>
				<%= entry.user.name %>
			</td>
			<td>
				<%# if entry.entryvotes.blank? %>
					<%= entry.vote_count %>		
				<%#else%>
					<%#= entry.entryvotes %>
				<%# end -%>
			</td>
		</tr>
		<% end -%>
	</table>
<% end %>

app/views/results/index.html.erb
<script type="text/javascript">
	 $(document).ready(function(){
    // the "href" attribute of .modal-trigger must specify the modal ID that wants to be triggered
    $('.upvote').modal();
  });      
</script>
<div class="col s12 m12 l12 center">
  <div class="col hide-on-small-and-down m1 l1 center">&nbsp;</div>
    <div class="col s12 m10 l10">
    <% if notice %>
      <p id="notice"><%= notice %></p>
    <% end %>
    </div>
  <div class="col hide-on-small-and-down m1 l1 center">&nbsp;</div>
</div>
<div class="col hide-on-small-and-below m1 l1">&nbsp;</div>
<div class="col s12 m10 l10 condesc" style="font-size:14px;">
	<div class="center">
		<h5>Results</h5>
		<% if current_user.role=="admin" || current_user.role=="Admin" %>
			<%= link_to "Admin Panel","/admin" %>
		<%end%>
	</div>
	<!--div class="center">
		<div class="form-horizontal">
		  <div class="form-group">
			  <%#= form_tag(results_path, :method => "get", id: "search-form") do %>
	            <label class="control-label col m3 l3">Enter Contests</label>
	            <%#= text_field_tag :search, params[:search], placeholder: "Search Contests",:class=>"form-control col m6 l6",:size=>24 %>
	          <!--i class="material-icons">search</i-->
	            <!--%#= button_tag( :class =>"btn") do %>
	              search
	            <%# end %>
	            <%#= submit_tag " Search ",:class=>"btn btn-success",:style=>"margin-left:0px;" %>
	          <%#end%>
	      </div>
	    </div>
	</div-->
	<table class="table-bordered sortable">
	<tr>
		<th width="5%">ID</th>
		<th width="10%">Type</th>
		<th width="15%">Contest Title</th>
		<th width="30%">Entry Details</th>
		<th width="10%">Vote Count</th>
		<th width="10%">Status</th>
		<th width="20%">Dates</th>
	</tr>
	<% @votes.each do |votes| %>
	<tr>
		<td><%= link_to votes.entry.contest.id, "/contests/#{votes.entry.contest.id}" %></td>
		<td><%= votes.entry.contest.contest_type %></td>
		<td><%= votes.entry.contest.title %></td>
		<td>
			<span style="color:grey;">Caption: </span><%= link_to votes.entry.caption, "/entries/#{votes.entry.id}" %><br>
			<!--span style="color:grey;">Name: </span><%#=  %><br>
			<span style="color:grey;">FB Email: </span><%#= votes.entry.user.email %><br-->
			<span style="color:grey;">Entry Email: </span><%= votes.entry.email %><br>
			<span style="color:grey;">Mobile : </span><%= votes.entry.mobile %><br>
		</td>
		<td>
			<% if votes.entry.entryvotes %> 
				<%= pluralize(votes.entry.entryvotes, "vote") %>
			<%else%>
				<%= pluralize(votes.entry.votes.count, "vote") %>
			<%end%><br>
			<% if current_user.role=="admin" || current_user.role=="Admin" %>
				<%= link_to "Overide",edit_entry_path(votes.entry.id)%>
			<%end%>
		</td>
		<td><%= votes.entry.contest.status.camelize %></td>
		<td>
			<b>Start Date</b>: <%= votes.entry.contest.start_date.to_date %><br>
			<b>End Date</b>: <%= votes.entry.contest.end_date.to_date %>
		</td>
	</tr>
	<% end %>
	</table>
</div>
<div class="col s12 m10 l10 pagination" style="text-align:right">
   <%= will_paginate @entry, renderer: BootstrapPagination::Rails %>
</div>
<div class="col hide-on-small-and-below m1 l1">&nbsp;</div>

app/views/results/winners.html.erb
<div class="col s12 m12 l12 center">
  <div class="col hide-on-small-and-down m1 l1 center">&nbsp;</div>
    <div class="col s12 m10 l10">
    <% if notice %>
      <p id="notice"><%= notice %></p>
    <% end %>
    </div>
  <div class="col hide-on-small-and-down m1 l1 center">&nbsp;</div>
</div>
<div class="col hide-on-small-and-below m1 l1">&nbsp;</div>
<div class="col s12 m10 l10 condesc" style="font-size:14px;">
	<div class="center">
		<h5>Find Winners By Contest Id</h5>
		<hr>
		<div class="col s3 m3 l3">&nbsp;</div>
		<div class="col s6 m6 l6">
			<%= form_tag(winners_path, :method => "get", id: "search-form") do %>
				<div class="col s6 m6 l6">
					<%= text_field_tag :search, params[:search], placeholder: "Enter Contest ID" %>
				</div>
				<div class="col s6 m6 l6 left-align">
					<%= submit_tag "Search", :class=>"btn" %>
				</div>
			<% end %>
		</div>
		<div class="col s3 m3 l3">&nbsp;</div>
	</div>
	<div class="col s12 m12 l12 center" style="margin-top:5%;">
		<% if @contests.present? %>
			<%= render "results/winnerlist" %>
		<% else %>
			<p class="center red-text">
				Please enter valid contest id to find top entries.<%#= params[:search] %>.
			</p>
		<% end %>
	</div>
</div>
<div class="col hide-on-small-and-below m1 l1">&nbsp;</div>