config/routes.rb
Rails.application.routes.draw do
  
  resources :updates

  resources :specialcontests

  resources :sponsorships

  resources :problems

  root :to => "contests#index"
  resources :entries
  resources :entries do
    member do
      post 'upvote'
      post 'overide'
      post 'testupvote'
    end
  end
  
  resources :results 
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
  get "/pages/:page" => "pages#show"
  get "/myentries" => "entries#mycontest"
  get "/admin" => "users#admin"
  get "/contestlist" => "contests#contestlist"
  get "/entrylist" => "entries#entrylist"
  get "/conentries" => "entries#conentries"
  get "/userlist" => "users#userlist"
  get "/users/edit/:id" => "users#edit"
  get "/winners" => "results#winners"
  get "makeadmin" => "users#makeadmin"
  get "makeparticipant" => "users#makeparticipant"
  resources :contests do
    resources :entries
  end

  match '*path' => 'errors#error_404', via: :all

  

end

app/views/layouts/_footer.html.erb
<div class="col hide-on-small-and-below m2 l2">&nbsp;</div>
<div class="col s12 m8 l8">
	<table>
		<tr>
			<td class="center"><%= link_to "Results",winners_path%></td>
			<td class="center"><%= link_to "Terms and Conditions","/pages/tnc"%></td>
			<td class="center"><%= link_to "Report a Problem", new_problem_path %></td>
			<td class="center"><%= link_to "Contact for Sponsorship", new_sponsorship_path %></td>
		</tr>
	</table>
	<p class="right">Created and Maintained by <a href="http://www.11d.co">11d Technologies</a></p>
	<!--p class="right">Created and Maintained by <%#= link_to(image_tag("logo/11d.png"))%></p-->
</div>
<div class="col hide-on-small-and-below m2 l2">&nbsp;</div>

app/views/layouts/_header.html.erb
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<script src="https://code.jquery.com/jquery-2.1.1.min.js" type="text/javascript"></script>
<script src="http://materializecss.com/templates/starter-template/js/init.js " type="text/javascript"></script>
<div class="navbar-fixed">
<nav role="navigation" class="nav font-gotham-medium">
  <ul class="site-links list-inline pull-left">
    <div class="hide-on-med-and-down">
      <%= link_to(image_tag("logo/KrazyKontest.png",:class=>"logo"),"/") %>
    </div>
    <a href="#" data-activates="mobile-view" id="button-collapse" class="black-text"><i class="material-icons">menu</i></a>
  </ul>

  <ul class="user-links list-inline pull-right black-text hide-on-med-and-down">
    <% if user_signed_in? %>
    	<li>
        Welcome <%= current_user.name %>
        <% if current_user.image? %>
          <%= image_tag(current_user.image,:class=>"responsive-img profile-pic-header") %>
        <%end%>
      </li>
      <% if current_user.admin? %>
        <li><%= link_to "Admin Panel", admin_path %></li>
      <% end %>
      <li><%= link_to "Your Entries","/myentries" %></li>
      <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
    <% else %>
        <li><%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path, :class=>"btn waves-effect waves-light" %></li>          
    <% end %>
  </ul>
  <ul class="side-nav" id="mobile-view">
    <% if user_signed_in? %>
      <li>
        Welcome <%= current_user.name %>
        <% if current_user.image? %>
          <%= image_tag(current_user.image,:class=>"responsive-img profile-pic-header") %>
        <%end%>
      </li>
      <% if current_user.admin? %>
        <li><%= link_to "Admin Panel", admin_path %></li>
      <% end %>
      <li><%= link_to "Your Entries","/myentries" %></li>
      <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
    <% else %>
        <li><%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path, :class=>"btn waves-effect waves-light" %></li>          
    <% end %>
  </ul>
</nav>
</div>
<script type="text/javascript">
$(document).ready(function(){
  $("#button-collapse").sideNav();
    });
</script>

app/views/layouts/_header_new.html.erb
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<script src="https://code.jquery.com/jquery-2.1.1.min.js" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/js/materialize.min.js"></script>
<script src="http://materializecss.com/templates/starter-template/js/init.js " type="text/javascript"></script>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.8&appId=679404752227654";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
 <nav>
  <div class="nav-wrapper">
    <%= link_to(image_tag("logo/KrazyKontest.png",:class=>"logo"),"/") %>
    <a href="#" data-activates="mobile-demo" class="button-collapse blue-text menu"><!--i class="material-icons">menu</i-->Menu</a>
    <ul class="right hide-on-med-and-down">
    
      <% if user_signed_in? %>
        <li>
          Welcome <%= current_user.name %>
          <% if current_user.image? %>
            <%= image_tag(current_user.image,:class=>"responsive-img profile-pic-header") %>
          <%end%>
        </li>
      <% if current_user.admin? %>
        <li><%= link_to "Admin Panel", admin_path %></li>
      <% end %>
        <li><%= link_to "Home","/" %></li>
        <li><%= link_to "Your Entries","/myentries" %></li>
        <li><%= link_to "Sponsor Contests",new_sponsorship_path %></li>
        <li><%= link_to "Results", "/winners" %></li>
        <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
      <% else %>
        <li><%= link_to "Home","/" %></li>
        <li><%= link_to "Your Entries","/myentries" %></li>
        <li><%= link_to "Sponsor Contests",new_sponsorship_path %></li>
        <li><%= link_to "Results", "/winners" %></li>          
      <% end %>
      <li style="padding-top:5%;">
        <iframe src="https://www.facebook.com/plugins/like.php?href=https%3A%2F%2Fwww.facebook.com%2Fkrazykontests%2F&width=106&layout=button_count&action=like&size=small&show_faces=true&height=46&appId=679404752227654" width="106" height="46" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true"></iframe>
      </li>
    </ul>
    <ul class="side-nav" id="mobile-demo">
      <% if user_signed_in? %>
        <li>
          Welcome <%= current_user.name %>
          <% if current_user.image? %>
            <%= image_tag(current_user.image,:class=>"responsive-img profile-pic-header") %>
          <%end%>
        </li>
      <% if current_user.admin? %>
        <li><%= link_to "Admin Panel", admin_path %></li>
      <% end %>
        <li><%= link_to "Home","/" %></li>
        <li><%= link_to "Your Entries","/myentries" %></li>
        <li><%= link_to "Sponsor Contests",new_sponsorship_path %></li>
        <li><%= link_to "Results", "/winners" %></li>
        <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
      <% else %>
        <li><%= link_to "Home","/" %></li>
        <li><%= link_to "Your Entries","/myentries" %></li>
        <li><%= link_to "Sponsor Contests",new_sponsorship_path %></li>
        <li><%= link_to "Results", "/winners" %></li>
        <!--li><%#= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path, :class=>"btn waves-effect waves-light" %></li-->          
      <% end %>
    </ul>
  </div>
</nav>
<script type="text/javascript">
$(document).ready(function(){
  //$("#button-collapse").sideNav();
  (function($){
  $(function(){

    $('.button-collapse').sideNav();

  }); // end of document ready
})(jQuery); // end of jQuery name space
    });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
    <% if yield(:title).present? %>
      <%= yield(:title) %>
    <%else%>
      Krazy Kontest - Participate in our contest and get a chance to win.
    <%end%>    
  </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flipclock/0.7.8/flipclock.min.css">
<!--link rel="stylesheet" href="/assets/flipclock.css"-->
  <%= csrf_meta_tags %>
  <% if yield(:meta_description).present? %>
    <meta name="description" content="<%= yield(:meta_description) %>" />
  <% else %>
    <meta name='description' content='GeT cRaZy GeT pRiZes. Cross the line, redefine, lose your mind and get crazy for this time.Participate in our contest and get a chance to win.'/>
  <% end %>
  <% if yield(:meta_keywords).present? %>
    <meta name="keywords" content="<%= yield(:meta_keywords) %>" />
  <% else %>
    <meta name='keywords' content='Krazy Kontest, crazy contest, contest, win contest, prizes, participate'/>
  <% end %>
  <meta name='copyright' content='Illusion Studios' />
  <meta name='language' content='ES'/>
  <meta name='robots' content='index,follow' />
  <meta name='designer' content='11D Technologies, http://www.11d.co' />
  <meta name='url' content='http://www.krazykontest.com' />
  <meta name='identifier-URL' content='http://www.krazykontest.com'>
  <meta property=“og:image” content='http://krazykontest.com/assets/logo/KrazyKontest.png'>
  <meta name="google-site-verification" content="E7-XuYKm1EfX_zWIR1Bs-m0xCGHsqi9cMQhcuhrcILA" />
</head>
<body>
<div id="main-container" class="container-flex">
	<div class="row">
		<%= render "layouts/header_new" %>
	</div>
	<div class="row page-wrap">
		<%= yield %>
	</div>
	<div class="row site-footer">
		<%= render "layouts/footer" %>
	</div>
</div>
</body>
</html>

app/views/layouts/entry.html.erb
<DOCTYPE html>
<html>
<head>
  <%= yield :head %>
  <title>
    <% if yield(:title).present? %>
      <%= yield(:title) %> - krazykontest.com
    <%else%>
      Krazy Kontest - Participate in our contest and get a chance to win.
    <%end%>    
  </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flipclock/0.7.8/flipclock.min.css">
<!--link rel="stylesheet" href="/assets/flipclock.css"-->
  <%= csrf_meta_tags %>
  <% if yield(:meta_description).present? %>
    <meta name="description" content="<%= yield(:meta_description) %>" />
  <% else %>
    <meta name='description' content='Latest entries on krazykontest.com'/>
  <% end %>
  <% if yield(:meta_keywords).present? %>
    <meta name="keywords" content="<%= yield(:meta_keywords) %>" />
  <% else %>
    <meta name='keywords' content='Krazy Kontest, crazy contest, contest, win contest, prizes, participate'/>
  <% end %>
  <meta name='copyright' content='Illusion Studios' />
  <meta name='language' content='ES'/>
  <meta name='robots' content='index,follow' />
  <meta name='designer' content='11D Technologies, http://www.11d.co' />
<meta property="og:site_name" content="http://www.krazykontest.com" />
</head>
<body>
<div id="main-container" class="container-flex">
        <div class="row">
                <%= render "layouts/header_new" %>
        </div>
        <div class="row page-wrap">
                <%= yield %>
        </div>
        <div class="row site-footer">
                <%= render "layouts/footer" %>
        </div>
</div>
</body>